"""Models Init

Revision ID: b56b159b0096
Revises: 
Create Date: 2025-05-27 19:48:31.076214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56b159b0096'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=15), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('discount', sa.DECIMAL(precision=3, scale=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=True)
    op.create_table('wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('material', sa.VARCHAR(length=25), nullable=False),
    sa.Column('discount', sa.DECIMAL(precision=3, scale=1), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category_title', sa.VARCHAR(length=15), nullable=False),
    sa.Column('collection_title', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['category_title'], ['categories.title'], ),
    sa.ForeignKeyConstraint(['collection_title'], ['collections.title'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('login', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('personal_discount', sa.DECIMAL(precision=3, scale=1), nullable=False),
    sa.Column('status', sa.Enum('bronze', 'silver', 'gold', 'diamond', name='statusenum'), nullable=False),
    sa.Column('total_costs', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=True),
    sa.Column('wishlist_id', sa.UUID(), nullable=True),
    sa.Column('signup_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('orders_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('purchase_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_orders_history_id'), 'orders_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_history_id'), table_name='orders_history')
    op.drop_table('orders_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
