"""Update: Simplification of restrictions on models parameters

Revision ID: d469b0a33dcb
Revises: ed2344299d90
Create Date: 2025-06-01 13:55:06.614252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd469b0a33dcb'
down_revision: Union[str, None] = 'ed2344299d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'title',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=35),
               existing_nullable=False)
    op.alter_column('collections', 'title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('products', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=35),
               existing_nullable=False)
    op.alter_column('products', 'color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'material',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('products', 'category_title',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=35),
               existing_nullable=False)
    op.alter_column('products', 'collection_title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'total_costs',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.DECIMAL(precision=8, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'total_costs',
               existing_type=sa.DECIMAL(precision=8, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('products', 'collection_title',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('products', 'category_title',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('products', 'material',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.DECIMAL(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'color',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('products', 'type',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.VARCHAR(length=35),
               existing_nullable=False)
    op.alter_column('collections', 'title',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('categories', 'title',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
